### ISSUE TITLE
kubeapi configuration update approach

### ISSUE THREAD

**Issue by koryaga** [Netcracker/KubeMarine#119]
Need to verify kubeapi restart approach, provide more robust if needed and generalize it

https://github.com/Netcracker/KubeMarine/blob/587479a0e227376acb402b77b9ecd6cf2ac96b59/kubemarine/psp.py#L356

**Comment by dmyar21** [comment]
https://github.com/Netcracker/KubeMarine/pull/275

**Comment by dmyar21** [comment]
pr: https://github.com/Netcracker/KubeMarine/pull/275
