### ISSUE TITLE
Get rid of cluster.inventory["nodes"][i]["connection"]

### ISSUE THREAD

**Issue by ilia1243** [Netcracker/KubeMarine#142]
We currently store fabric connection object directly in inventory. See defaults.apply_defaults():

```
cluster.inventory["nodes"][i]["connection"] = cluster.make_group([address])
```

This already caused some problems:

- necessity to remove this object in finalize inventory procedure (defauls.prepare_for_dump())
- after inventory is finalized, methods which require this key, become not working.
- if defauls.prepare_for_dump() is invoked with copy=True, this fabric connection is deep copied, which is undefined behaviour (at least, untill we prove that fabric allows such copying and this will not be broken during future upgrades of fabric).

Instead, I suggest to either entirely get rid of such caches of connections, or use other storage, for example cluster.context.

**Comment by dmyar21** [comment]
@ilia1243 Actual problem?
