### ISSUE TITLE
Node-specific kubeadm configuration options for control-plane manifests 

### ISSUE THREAD

**Issue by theboringstuff** [Netcracker/KubeMarine#180]
Currently in kubeadm configuration we use node-specific `--bind-address` configuration option for `kube-apiserver` manifest. This option is always set to first master IP address, so we have to remember to `sed` it on each `kube-apiserver` manifest re-creation/upgrade. 

The kubernetes way to configure and persist node-specific kubeadm configuration options for control-plane manifests is to use `patches`: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches. We should probably use `patches` instead of `sed` for `--bind-address` and other node-specific options.

**Comment by n549** [comment]
Implemented in https://github.com/Netcracker/KubeMarine/pull/352
