### ISSUE TITLE
no connection timeout for third party download

### ISSUE THREAD

**Issue by marniks7** [Netcracker/KubeMarine#230]
Hi,
When target environment doesn't have connection to the internet installation can fail.

ER: fail in X seconds
AR: failed in 5 minutes

I expect to have some reasonable connection timeout for curl

![image](https://user-images.githubusercontent.com/9289172/191827442-aeb49d0e-fe80-4b34-bb10-076ef967b25b.png)

**Comment by koryaga** [comment]
Hi,
Yepp, looks there is an opportunity  to make a requirement here https://github.com/Netcracker/KubeMarine/blob/af4c4de45fdd7aa32f53841a020f2d0bbdd7ed0d/kubemarine/thirdparties.py#L139
Thnks for reporting

**Comment by koryaga** [comment]
fixed
