### ISSUE TITLE
Provide docker image and docs how to use it

### ISSUE THREAD

**Issue by marniks7** [Netcracker/KubeMarine#244]
Hi,
Could you please provide ready-to-use docker image and documentation how to use kubemarine with that docker image

I have managed to build, and figure out how to do that, but that took time.
```bash
docker run \
--mount type=bind,source="$PWD",target="$PWD",readonly \
--mount type=bind,source="$HOME/.ssh",target=/home/root/.ssh,readonly \
kubemarine install -c runner/cluster.yaml
```

where `/home/root/.ssh` is used inside ` runner/cluster.yaml` the following way:
```
node_defaults:
  keyfile: "/home/root/.ssh/my.key"
  username: "centos"
```

**Comment by koryaga** [comment]
Hi, as for docker image, there are publushed here https://github.com/Netcracker/KubeMarine/pkgs/container/kubemarine in regular manner. 
And as for documentation  yes, looks like we have a gap here. Will make an update. Thank you

**Comment by koryaga** [comment]
Pls use https://github.com/Netcracker/KubeMarine#kubemarine-docker-installation
