### ISSUE TITLE
root user in the Dockerfile

### ISSUE THREAD

**Issue by alekslebedev** [Netcracker/KubeMarine#245]
Hi, team!
Using a **root** user in the [Dockerfile](https://github.com/Netcracker/KubeMarine/blob/9369b0edf02d8b25a41cb396decbef4094c44f00/Dockerfile#L8) is not a best practice. Is this really required ?

**Comment by koryaga** [comment]
#256

**Comment by koryaga** [comment]
resolved in 0.9.0
