### ISSUE TITLE
single  binary delivery

### ISSUE THREAD

**Issue by koryaga** [Netcracker/KubeMarine#259]
Need to provide single binary based on https://pyinstaller.org/en/stable/  as a deliverable for kubemarine. 
Configuration file https://github.com/Netcracker/KubeMarine/blob/main/kubemarine.spec
DoD:
1. build procedure is done. Manual steps and doc changes
2. all kubemarine procedures are available from single binary
3. automatic build process is done. Binary is published under Relese page(Assets)

**Comment by dmyar21** [comment]
https://github.com/Netcracker/KubeMarine/pull/266
