### ISSUE TITLE
check-paas thirdparties improve

### ISSUE THREAD

**Issue by koryaga** [Netcracker/KubeMarine#299]
If new default 3rd-party is added, but this section is forgotten to update, check_paas will consider 3rd-party as not default and won't check recommended versions. It will not even fail in this case, right?
On the other hand, we are starting to move the list of default 3rd-parties from defaults to globals and can complete this rework.
* Move the whole section without `sha` from default to globals.
* Add new enrichment procedure before defaults.compile_inventory which will
    * Copy default 3rd-party from global to inventory, if it is not defined by user.
    * Added recommended sha using thirdparties.get_thirdparty_recommended_sha if source is not defined by user.
* check_paas will use the same thirdparties.get_thirdparty_recommended_sha

_Originally posted by @ilia1243 in https://github.com/Netcracker/KubeMarine/pull/227#discussion_r1024907165_

**Comment by ilia1243** [comment]
Closing as very unimportant. May be done as part of possible future rework of defaults.yaml and jinja templates.
