### ISSUE TITLE
Fix unpack of .zip thirdparties

### ISSUE THREAD

**Issue by ilia1243** [Netcracker/KubeMarine#365]
Need to:
* Fix reinstallation of .zip thirdparties. Currently it [waits](https://github.com/Netcracker/KubeMarine/blob/0.13.0/kubemarine/thirdparties.py#L203) forever.
* `mode` and `owner` options of thirdparties [do not work](https://github.com/Netcracker/KubeMarine/blob/0.13.0/kubemarine/thirdparties.py#L209) for .zip.
* Add [check SHA](https://github.com/Netcracker/KubeMarine/blob/0.13.0/kubemarine/procedures/check_paas.py#L388) of zip archive content.

**Comment by pranavcracker** [comment]
A draft pull request has been raised to fix the issue
https://github.com/Netcracker/KubeMarine/pull/379

**Comment by pranavcracker** [comment]
Code changes for fixing reinstallation of .zip thirdparties have been done.
Now working on handling `mode` and `owner` options for .zip files.

**Comment by pranavcracker** [comment]
Additional code has been added to handle `mode` and `owner` options for **.zip** files.
Waiting for review on the code changes.

**Comment by pranavcracker** [comment]
Adding additional code for verifying the hash (SHA1) for zip archive contents before and after unpacking.
Waiting for review on the code changes.
