### ISSUE TITLE
Add sysctl and audit rules validation

### ISSUE THREAD

**Issue by iLeonidze** [Netcracker/KubeMarine#42]
We have to add sysctl and audit rules validation before kubernetes installation. Validations should be added to checks too. Audit rules should be verified only via `auditctl`

**Comment by ilia1243** [comment]
Experienced issue with this while adopting RHEL 9 #473

During Kubemarine installation we apply sysctl config using `sudo sysctl -p` which bypasses the SELinux security.
During boot, this config file is read by `/usr/lib/systemd/systemd-sysctl` under specific SELinux context.

We thus might have working cluster after installation, but not working after reboot. The problem can be demonstrated
```sh
[cloud-user@k8s-control-plane-1 ~]$ sudo sysctl -p /etc/sysctl.d/98-kubemarine-sysctl.conf > /dev/null; echo $?
0
[cloud-user@k8s-control-plane-1 ~]$ sudo chcon -t user_tmp_t /etc/sysctl.d/98-kubemarine-sysctl.conf
[cloud-user@k8s-control-plane-1 ~]$ runcon -r system_r -t systemd_sysctl_t /usr/lib/systemd/systemd-sysctl; echo $?
1
[cloud-user@k8s-control-plane-1 ~]$ sudo sysctl -p /etc/sysctl.d/98-kubemarine-sysctl.conf > /dev/null; echo $?
0
[cloud-user@k8s-control-plane-1 ~]$
```
